using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Vidly.DTOs;
using Vidly.Models;

namespace Vidly.Controllers.Api
{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        //response: GET/api/customer
        public IHttpActionResult GetCustomer()
        {
            var customerDtos = _context.Customers
                .Include(c => c.MembershipType)
                .ToList()
                .Select(Mapper.Map<Customer, CustomerDto>); //parentheses remove - we dont call this method here. it's reference to this method (we delegate this method)
                                                                                                      //<source, target types>
            return Ok(customerDtos);
        }

        //GET/api/customers/1
        public IHttpActionResult GetCustomers(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return NotFound();

            return Ok(Mapper.Map<Customer, CustomerDto> (customer));
        }

        //POST/api/customers
        [HttpPost] //because we create resource. to apply this attribute here this action will be only called is we sent httppost request
        //the alternative rename method public Customer CreateCustomer(Customer customer) to PostCustomer (Microsoft tutorials)
        public IHttpActionResult CreateCustomer(CustomerDto customerDto)//we post to customer collection
        {
            if (!ModelState.IsValid)
                return BadRequest();

            //for mapp this dto back to domain object
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);

            _context.Customers.Add(customer);
            _context.SaveChanges();

            //this cusmomer has id that generated by the db so we add this id in dto and return to the client
            customerDto.Id = customer.Id;

            return Created(new Uri(Request.RequestUri + "/" + customer.Id), customerDto);
        }

        //PUT/api/customers/1
        //can return customer or void
        [HttpPut]
        public IHttpActionResult Update(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                return NotFound();

            Mapper.Map(customerDto, customerInDb); //(source object, target object)
            
            _context.SaveChanges();

            return Ok();
        }

        //DELETE/api/cuatomers/1
        [HttpDelete]
        public IHttpActionResult DeleteCustomer(int id)
        {
            //check is it exist or not
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customerInDb == null)
                return NotFound();

            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();

            return Ok();
        }

    }
}
